//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.01 at 11:34:30 PM CEST 
//


package hu.uszeged.inf.iot.simulator.xmlgenerator;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="appliance" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="xcoord" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="ycoord" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="parentApp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="applications">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="application" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="parentDevice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="tasksize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="neighbourAppliances">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="device" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="deviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appliance"
})
@XmlRootElement(name = "appliances")
public class Appliances {

    protected List<Appliances.Appliance> appliance;

    /**
     * Gets the value of the appliance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appliance property.
      * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppliance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Appliances.Appliance }
     * 
     * 
     */
    public List<Appliances.Appliance> getAppliance() {
        if (appliance == null) {
            appliance = new ArrayList<Appliances.Appliance>();
        }
        return this.appliance;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="xcoord" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="ycoord" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="parentApp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="applications">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="application" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="parentDevice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="tasksize" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="neighbourAppliances">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="device" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="deviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "xcoord",
        "ycoord",
        "parentApp",
        "file",
        "applications",
        "neighbourAppliances"
    })
    public static class Appliance {

    	@XmlTransient
    	protected int level;
    	
    	
    	public int getLevel() {
    		return level;
    	}
    	
    	public void setLevel(int level) {
    		this.level = level;
    	}
    	
        @XmlElement(required = true)
        protected String name;
        protected double xcoord;
        protected double ycoord;
        @XmlElement(required = true)
        protected String parentApp;
        @XmlElement(required = true)
        protected String file;
        @XmlElement(required = true)
        protected Appliances.Appliance.Applications applications;
        @XmlElement(required = true)
        protected Appliances.Appliance.NeighbourAppliances neighbourAppliances;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the xcoord property.
         * 
         */
        public double getXcoord() {
            return xcoord;
        }

        /**
         * Sets the value of the xcoord property.
         * 
         */
        public void setXcoord(double value) {
            this.xcoord = value;
        }

        /**
         * Gets the value of the ycoord property.
         * 
         */
        public double getYcoord() {
            return ycoord;
        }

        /**
         * Sets the value of the ycoord property.
         * 
         */
        public void setYcoord(double value) {
            this.ycoord = value;
        }

        /**
         * Gets the value of the parentApp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentApp() {
            return parentApp;
        }

        /**
         * Sets the value of the parentApp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentApp(String value) {
            this.parentApp = value;
        }

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the applications property.
         * 
         * @return
         *     possible object is
         *     {@link Appliances.Appliance.Applications }
         *     
         */
        public Appliances.Appliance.Applications getApplications() {
            return applications;
        }

        /**
         * Sets the value of the applications property.
         * 
         * @param value
         *     allowed object is
         *     {@link Appliances.Appliance.Applications }
         *     
         */
        public void setApplications(Appliances.Appliance.Applications value) {
            this.applications = value;
        }

        /**
         * Gets the value of the neighbourAppliances property.
         * 
         * @return
         *     possible object is
         *     {@link Appliances.Appliance.NeighbourAppliances }
         *     
         */
        public Appliances.Appliance.NeighbourAppliances getNeighbourAppliances() {
            return neighbourAppliances;
        }

        /**
         * Sets the value of the neighbourAppliances property.
         * 
         * @param value
         *     allowed object is
         *     {@link Appliances.Appliance.NeighbourAppliances }
         *     
         */
        public void setNeighbourAppliances(Appliances.Appliance.NeighbourAppliances value) {
            this.neighbourAppliances = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="application" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="parentDevice" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="tasksize" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "application"
        })
        public static class Applications {

            protected List<Appliances.Appliance.Applications.Application> application;

            /**
             * Gets the value of the application property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the application property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getApplication().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Appliances.Appliance.Applications.Application }
             * 
             * 
             */
            public List<Appliances.Appliance.Applications.Application> getApplication() {
                if (application == null) {
                    application = new ArrayList<Appliances.Appliance.Applications.Application>();
                }
                return this.application;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="parentDevice" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="tasksize" type="{http://www.w3.org/2001/XMLSchema}int" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "type",
                "name",
                "parentDevice",
                "freq",
                "instance"
            })
            public static class Application {

                @XmlElement(required = true)
                protected String type;
                @XmlElement(required = true)
                protected String name;
                @XmlElement(required = true)
                protected String parentDevice;
                protected int freq;
                @XmlElement(required = true)
                protected String instance;
                @XmlAttribute(name = "tasksize")
                protected Integer tasksize;

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the parentDevice property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getParentDevice() {
                    return parentDevice;
                }

                /**
                 * Sets the value of the parentDevice property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setParentDevice(String value) {
                    this.parentDevice = value;
                }

                /**
                 * Gets the value of the freq property.
                 * 
                 */
                public int getFreq() {
                    return freq;
                }

                /**
                 * Sets the value of the freq property.
                 * 
                 */
                public void setFreq(int value) {
                    this.freq = value;
                }

                /**
                 * Gets the value of the instance property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInstance() {
                    return instance;
                }

                /**
                 * Sets the value of the instance property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInstance(String value) {
                    this.instance = value;
                }

                /**
                 * Gets the value of the tasksize property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getTasksize() {
                    return tasksize;
                }

                /**
                 * Sets the value of the tasksize property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setTasksize(Integer value) {
                    this.tasksize = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="device" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="deviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "device"
        })
        public static class NeighbourAppliances {

            protected List<Appliances.Appliance.NeighbourAppliances.Device> device;

            /**
             * Gets the value of the device property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the device property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDevice().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Appliances.Appliance.NeighbourAppliances.Device }
             * 
             * 
             */
            public List<Appliances.Appliance.NeighbourAppliances.Device> getDevice() {
                if (device == null) {
                    device = new ArrayList<Appliances.Appliance.NeighbourAppliances.Device>();
                }
                return this.device;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="deviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "deviceName"
            })
            public static class Device {

                @XmlElement(required = true)
                protected String deviceName;

                /**
                 * Gets the value of the deviceName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDeviceName() {
                    return deviceName;
                }

                /**
                 * Sets the value of the deviceName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDeviceName(String value) {
                    this.deviceName = value;
                }

            }

        }

    }

}
