//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.02 at 06:21:08 AM CEST 
//


package hu.u_szeged.inf.fog.simulator.xmlgenerator;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="device" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="sensor" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="maxinbw" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="maxoutbw" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="diskbw" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="reposize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ratio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="strategy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="xCoord" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="yCoord" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="shutdown">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="stoptime" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="filesize" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "device"
})
@XmlRootElement(name = "devices")
public class Devices {

    protected List<Devices.Device> device;

    /**
     * Gets the value of the device property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the device property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDevice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Devices.Device }
     * 
     * 
     */
    public List<Devices.Device> getDevice() {
        if (device == null) {
            device = new ArrayList<Devices.Device>();
        }
        return this.device;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="freq" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="sensor" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="maxinbw" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="maxoutbw" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="diskbw" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="reposize" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ratio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="strategy" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="xCoord" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="yCoord" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="shutdown">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="stoptime" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="filesize" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "freq",
        "sensor",
        "maxinbw",
        "maxoutbw",
        "diskbw",
        "reposize",
        "ratio",
        "strategy",
        "xCoord",
        "yCoord",
        "shutdown"
    })
    public static class Device {

        @XmlElement(required = true)
        protected String name;
        protected int freq;
        protected int sensor;
        protected short maxinbw;
        protected short maxoutbw;
        protected short diskbw;
        protected int reposize;
        protected int ratio;
        @XmlElement(required = true)
        protected String strategy;
        protected double xCoord;
        protected double yCoord;
        @XmlElement(required = true)
        protected Devices.Device.Shutdown shutdown;
        @XmlAttribute(name = "starttime")
        protected Integer starttime;
        @XmlAttribute(name = "stoptime")
        protected Integer stoptime;
        @XmlAttribute(name = "number")
        protected Short number;
        @XmlAttribute(name = "filesize")
        protected Integer filesize;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the freq property.
         * 
         */
        public int getFreq() {
            return freq;
        }

        /**
         * Sets the value of the freq property.
         * 
         */
        public void setFreq(int value) {
            this.freq = value;
        }

        /**
         * Gets the value of the sensor property.
         * 
         */
        public int getSensor() {
            return sensor;
        }

        /**
         * Sets the value of the sensor property.
         * 
         */
        public void setSensor(int value) {
            this.sensor = value;
        }

        /**
         * Gets the value of the maxinbw property.
         * 
         */
        public short getMaxinbw() {
            return maxinbw;
        }

        /**
         * Sets the value of the maxinbw property.
         * 
         */
        public void setMaxinbw(short value) {
            this.maxinbw = value;
        }

        /**
         * Gets the value of the maxoutbw property.
         * 
         */
        public short getMaxoutbw() {
            return maxoutbw;
        }

        /**
         * Sets the value of the maxoutbw property.
         * 
         */
        public void setMaxoutbw(short value) {
            this.maxoutbw = value;
        }

        /**
         * Gets the value of the diskbw property.
         * 
         */
        public short getDiskbw() {
            return diskbw;
        }

        /**
         * Sets the value of the diskbw property.
         * 
         */
        public void setDiskbw(short value) {
            this.diskbw = value;
        }

        /**
         * Gets the value of the reposize property.
         * 
         */
        public int getReposize() {
            return reposize;
        }

        /**
         * Sets the value of the reposize property.
         * 
         */
        public void setReposize(int value) {
            this.reposize = value;
        }

        /**
         * Gets the value of the ratio property.
         * 
         */
        public int getRatio() {
            return ratio;
        }

        /**
         * Sets the value of the ratio property.
         * 
         */
        public void setRatio(int value) {
            this.ratio = value;
        }

        /**
         * Gets the value of the strategy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStrategy() {
            return strategy;
        }

        /**
         * Sets the value of the strategy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStrategy(String value) {
            this.strategy = value;
        }

        /**
         * Gets the value of the xCoord property.
         * 
         */
        public double getXCoord() {
            return xCoord;
        }

        /**
         * Sets the value of the xCoord property.
         * 
         */
        public void setXCoord(double value) {
            this.xCoord = value;
        }

        /**
         * Gets the value of the yCoord property.
         * 
         */
        public double getYCoord() {
            return yCoord;
        }

        /**
         * Sets the value of the yCoord property.
         * 
         */
        public void setYCoord(double value) {
            this.yCoord = value;
        }

        /**
         * Gets the value of the shutdown property.
         * 
         * @return
         *     possible object is
         *     {@link Devices.Device.Shutdown }
         *     
         */
        public Devices.Device.Shutdown getShutdown() {
            return shutdown;
        }

        /**
         * Sets the value of the shutdown property.
         * 
         * @param value
         *     allowed object is
         *     {@link Devices.Device.Shutdown }
         *     
         */
        public void setShutdown(Devices.Device.Shutdown value) {
            this.shutdown = value;
        }

        /**
         * Gets the value of the starttime property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Integer getStarttime() {
            return starttime;
        }

        /**
         * Sets the value of the starttime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setStarttime(Integer value) {
            this.starttime = value;
        }

        /**
         * Gets the value of the stoptime property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getStoptime() {
            return stoptime;
        }

        /**
         * Sets the value of the stoptime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setStoptime(Integer value) {
            this.stoptime = value;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setNumber(Short value) {
            this.number = value;
        }

        /**
         * Gets the value of the filesize property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Integer getFilesize() {
            return filesize;
        }

        /**
         * Sets the value of the filesize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setFilesize(Integer value) {
            this.filesize = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "number",
            "from",
            "to"
        })
        public static class Shutdown {

            protected int number;
            protected int from;
            protected int to;

            /**
             * Gets the value of the number property.
             * 
             */
            public int getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             */
            public void setNumber(int value) {
                this.number = value;
            }

            /**
             * Gets the value of the from property.
             * 
             */
            public int getFrom() {
                return from;
            }

            /**
             * Sets the value of the from property.
             * 
             */
            public void setFrom(int value) {
                this.from = value;
            }

            /**
             * Gets the value of the to property.
             * 
             */
            public int getTo() {
                return to;
            }

            /**
             * Sets the value of the to property.
             * 
             */
            public void setTo(int value) {
                this.to = value;
            }

        }

    }

}
